name: EasyGamemode
author: noogotte
version: 1.7

main: fr.noogotte.easygamemode.EasyGamemode
 
commands:
    easygamemode:
        description: "Commande principale"
        usage: "gm"
    "easygamemode gamemode":
        description: "Change votre gamemode"
        usage: ""
        permission: "easyG.cmd.gamemode"
        aliases: ["gm", "eg"]
        
permissions:
    easyG.cmd.*:
        default: op
        children:
            easyG.SignPlace: true
            easyG.SignUse: true
            easyG.cmd.gamemode: true
            easyG.cmd.fly: true
    easyG.cmd.gamemode:
        default: op
    easyG.cmd.fly:
        default: op
    easyG.SignPlace:
        default: op
    easyG.SignUse:
        default: op